# Generated by Django 5.2.1 on 2025-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='channel_preference',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
