# Generated by Django 5.2.1 on 2025-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_remove_beneficiary_channel_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='infobip_synced',
            field=models.BooleanField(default=False),
        ),
    ]
