# Generated by Django 5.2.1 on 2025-05-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_remove_beneficiary_channel_preference_and_more'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.AddField(
            model_name='survey',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='content',
            field=models.TextField(default='Survey content goes here', help_text='Survey questions or instructions.'),
        ),
        migrations.CreateModel(
            name='SurveyDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
