# Generated by Django 5.2.1 on 2026-03-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_infobip_synced'),
        ('surveys', '0004_remove_surveyquestion_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('WHATSAPP_TEMPLATE', 'WhatsApp Template')], default='WHATSAPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='beneficiaries.beneficiary'),
        ),
    ]
